name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['test', 'prod']
    outputs:
      runner_type: ${{ steps.set-runner.outputs.runner_type }}
    steps:
    - name: Map environment to runner
      id: set-runner
      run: |
        if [ "${{ matrix.environment }}" == "prod" ]; then
          echo "::set-output name=runner_type::ubuntu-latest"
        else
          echo "::set-output name=runner_type::ubuntu-latest"
        fi

  terraform:
    needs: setup
    runs-on: ${{ needs.setup.outputs.runner_type }}
    strategy:
      matrix:
        environment: ['test', 'prod']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.4

    - name: Terraform Init
      run: |
        cd terraform/env/${{ matrix.environment }}
        terraform init

    - name: Terraform Workspace Select
      run: |
        cd terraform/env/${{ matrix.environment }}
        terraform workspace select ${{ matrix.environment }} || terraform workspace new ${{ matrix.environment }}
        
    - name: Terraform Plan
      run: |
        cd terraform/env/${{ matrix.environment }}
        terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' 
      run: terraform apply -auto-approve tfplan