name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test, prod]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.4

    - name: Terraform Init
      run: |
        cd terraform/env/${{ matrix.environment }}
        terraform init

    - name: Terraform Workspace Select
      run: |
        cd terraform/env/${{ matrix.environment }}
        terraform workspace select ${{ matrix.environment }} || terraform workspace new ${{ matrix.environment }}
        
    - name: Terraform Plan
      run: |
        cd terraform/env/${{ matrix.environment }}
        terraform plan -out=tfplan

    - name: Terraform Apply
      if: matrix.environment == 'test'
      run: |
        cd terraform/env/${{ matrix.environment }}
        terraform apply tfplan